// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxJKWeM-PKHv1qNlyU2ZogtB4AArVOuzI',
    appId: '1:1044486893591:android:fae16da7c47e1bb8926c52',
    messagingSenderId: '1044486893591',
    projectId: 'truster-app-dev',
    storageBucket: 'truster-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiENpFOn2REtAYCRib6EWHG6B65inBdws',
    appId: '1:1044486893591:ios:d355d5c0dc9423f4926c52',
    messagingSenderId: '1044486893591',
    projectId: 'truster-app-dev',
    storageBucket: 'truster-app-dev.appspot.com',
    androidClientId: '1044486893591-v8ajtvu8an9sbejloe1sllepuupno38q.apps.googleusercontent.com',
    iosClientId: '1044486893591-5oj1cgr30dod9tcrma3qifb8j9jh3kh5.apps.googleusercontent.com',
    iosBundleId: 'com.truster.trusterApps',
  );
}
